export const ICONS = {
  logo: require('./icons/logo.png'),
  coverViewIcon: require('./icons/coverViewIcon.png'),
  bigCoverViewIcon: require('./icons/bigCoverViewIcon.png'),
  detailsViewIcon: require('./icons/detailsViewIcon.png'),
  sidebarHandleIcon: require('./icons/sidebarHandleIcon.png'),
  searchIcon: require('./icons/searchIcon.png'),
  open: require('./icons/openIcon.png'),
  save: require('./icons/saveIcon.png'),
  plus: require('./icons/plusIcon.png'),
  arrow: require('./icons/arrow.png'),
  circlePlus: require('./icons/circlePlus.png'),
  x: require('./icons/x.png'),
  minus: require('./icons/minus.png'),
  maximize: require('./icons/maximize.png'),
}
